FROM flink:1.16.3

# install python3: it has updated Python to 3.9 in Debian 11 and so install Python 3.7 from source
# it currently only supports Python 3.6, 3.7 and 3.8 in PyFlink officially.

# install python3 and pip3
RUN apt-get update -y && \
apt-get install -y python3 python3-pip python3-dev && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python3 /usr/bin/python


# Update the package repository and install OpenJDK 11 JDK, its required by the JDBC connector
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean

# Optionally set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH


# install PyFlink
RUN pip3 install apache-flink==1.16.3

# COPY apache-flink*.tar.gz /
# RUN pip3 install /apache-flink-libraries*.tar.gz